/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB10;

import BAB9.*;
import BAB8.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @@author mufi
 */
public class GUI_Kelola extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Kelola
     */
    public GUI_Kelola() {
        initComponents();
                DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();
        int rowCount = dataModel.getRowCount();
        while(rowCount > 0){
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount();
        }
    }
    public Connection conn;
    
    public void koneksi() throws SQLException {
        try {
            conn = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/kelola_keuangan?user=root&password=");
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException e) {
            Logger.getLogger(GUI_Register.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception es) {
            Logger.getLogger(GUI_Register.class.getName()).log(Level.SEVERE, null, es);
        }
    }
    
    public void clear(){
        txt_id.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_saldoawal.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        cmb_jenkel = new javax.swing.JComboBox<>();
        txt_alamat = new javax.swing.JTextField();
        txt_saldoawal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbm = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_tambahsaldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_tambahsaldo = new javax.swing.JButton();
        btn_tariksaldo = new javax.swing.JButton();
        txt_tariksaldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        cmb_jenkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jenkelActionPerformed(evt);
            }
        });

        jLabel1.setText("ID                       :");

        jLabel2.setText("Nama                :");

        jLabel3.setText("Jenis Kelamin   :");

        jLabel4.setText("Alamat              :");

        jLabel5.setText("Saldo Awal       :");

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pendataan Keuangan Pribadi");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID User", "Nama User", "Jenis Kelamin", "Alamat User", "Status", "Saldo Awal", "Jumlah", "Saldo Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbm);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_tambahsaldo.setText("0");

        jLabel6.setText("Tambah Saldo :");

        btn_tambahsaldo.setText("Tambah ");
        btn_tambahsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahsaldoActionPerformed(evt);
            }
        });

        btn_tariksaldo.setText("Tarik");
        btn_tariksaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tariksaldoActionPerformed(evt);
            }
        });

        txt_tariksaldo.setText("0");

        jLabel7.setText("Tarik Saldo       :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_tambahsaldo)
                            .addComponent(txt_tambahsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tariksaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tariksaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tambahsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_tambahsaldo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tariksaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tariksaldo)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btnSearch.setText("Search 🔍");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_id)
                                        .addComponent(txt_nama)
                                        .addComponent(cmb_jenkel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_alamat)
                                        .addComponent(txt_saldoawal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_cetak))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(300, 300, 300))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose)
                            .addComponent(btn_hapus))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_jenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_saldoawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahsaldoActionPerformed

        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();
int row = tbm.getSelectedRow();

try {
    koneksi(); // Membuat koneksi ke database

    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Pilih baris terlebih dahulu.");
    }

    // Mendapatkan data dari input pengguna
    String idUser = (String) dataModel.getValueAt(row, 0);
    double saldoAwal = (double) dataModel.getValueAt(row, 5);
    double tambah = Double.parseDouble(txt_tambahsaldo.getText());

    // Update saldo di database
    String updateSql = "UPDATE Data_nasabah SET Saldo = ? WHERE ID_User = ?";
    PreparedStatement updateStatement = conn.prepareStatement(updateSql);
    updateStatement.setDouble(1, saldoAwal + tambah);
    updateStatement.setString(2, idUser);
    updateStatement.executeUpdate();

    // Update saldo di tabel
    double saldoAkhir = saldoAwal + tambah;
    dataModel.setValueAt("Tambah", row, 4);
    dataModel.setValueAt(tambah, row, 6);
    dataModel.setValueAt(saldoAkhir, row, 7);

    clear();
    JOptionPane.showMessageDialog(this, "Saldo berhasil ditambahkan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);

    // Setel nilai JTextField kembali ke 0
    txt_tambahsaldo.setText("0");
} catch (SQLException | NumberFormatException e) {
    // Tangani exception dengan menampilkan pesan menggunakan JOptionPane
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
    }//GEN-LAST:event_btn_tambahsaldoActionPerformed

    private void btn_tariksaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tariksaldoActionPerformed
    
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();
int row = tbm.getSelectedRow();

try {
    koneksi(); // Membuat koneksi ke database

    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Pilih baris terlebih dahulu.");
    }

    // Mendapatkan data dari input pengguna
    String idUser = (String) dataModel.getValueAt(row, 0);
    double saldoAwal = (double) dataModel.getValueAt(row, 7); // Menggunakan saldo akhir sebagai saldo awal
    double tarik = Double.parseDouble(txt_tariksaldo.getText());

    if (saldoAwal < tarik) {
        JOptionPane.showMessageDialog(this, "Saldo tidak mencukupi untuk penarikan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Tidak melanjutkan proses jika saldo tidak mencukupi
    }

    // Update saldo di database
    String updateSql = "UPDATE Data_nasabah SET Saldo = ? WHERE ID_User = ?";
    PreparedStatement updateStatement = conn.prepareStatement(updateSql);
    updateStatement.setDouble(1, saldoAwal - tarik);
    updateStatement.setString(2, idUser);
    updateStatement.executeUpdate();

    // Update saldo di tabel
    double saldoAkhir = saldoAwal - tarik;
    dataModel.setValueAt("Tarik", row, 4);
    dataModel.setValueAt(tarik, row, 6);
    dataModel.setValueAt(saldoAkhir, row, 7);

    clear();
    JOptionPane.showMessageDialog(this, "Saldo berhasil ditarik.", "Informasi", JOptionPane.INFORMATION_MESSAGE);

    // Setel nilai JTextField kembali ke 0
    txt_tariksaldo.setText("0");
} catch (SQLException | NumberFormatException e) {
    // Tangani exception dengan menampilkan pesan menggunakan JOptionPane
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btn_tariksaldoActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
     // TODO add your handling code here:
     DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();

try {
    koneksi(); // Membuat koneksi ke database

    // Menyiapkan pernyataan SQL untuk menyisipkan data ke database
    String insertSql = "INSERT INTO Data_nasabah (ID_User, Nama, Jenis_Kelamin, Alamat, Saldo) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement preparedStatement = conn.prepareStatement(insertSql);

    // Mendapatkan data dari input pengguna
    String idUser = txt_id.getText();
    String nama = txt_nama.getText();
    String jenisKelamin = cmb_jenkel.getSelectedItem().toString();
    String alamat = txt_alamat.getText();
    double saldo = Double.parseDouble(txt_saldoawal.getText());

    // Menjalankan pernyataan SQL untuk memeriksa apakah ID_User sudah ada
    String checkIdSql = "SELECT COUNT(*) FROM Data_nasabah WHERE ID_User = ?";
    PreparedStatement checkIdStatement = conn.prepareStatement(checkIdSql);
    checkIdStatement.setString(1, idUser);

    ResultSet resultSet = checkIdStatement.executeQuery();
    resultSet.next();
    int idCount = resultSet.getInt(1);

    // Periksa apakah ID_User sudah ada di database
    if (idCount > 0) {
        JOptionPane.showMessageDialog(this, "ID_User sudah ada. Pilih ID_User yang unik.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Hentikan eksekusi jika ID_User sudah ada
    }

    // Periksa apakah semua input sudah diisi
    if (idUser.isEmpty() || nama.isEmpty() || jenisKelamin.isEmpty() || alamat.isEmpty() || txt_saldoawal.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi semua kolom dengan benar.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Hentikan eksekusi jika ada yang kosong
    }

    // Mengatur parameter pada pernyataan SQL
    preparedStatement.setString(1, idUser);
    preparedStatement.setString(2, nama);
    preparedStatement.setString(3, jenisKelamin);
    preparedStatement.setString(4, alamat);
    preparedStatement.setDouble(5, saldo);

    // Menjalankan pernyataan SQL untuk menyisipkan data
    int affectedRows = preparedStatement.executeUpdate();

    if (affectedRows > 0) {
        // Menambahkan data ke tabel
        List<Object> list = new ArrayList<>();
        list.add(idUser);
        list.add(nama);
        list.add(jenisKelamin);
        list.add(alamat);
        list.add("Saldo Awal");
        list.add(saldo);
        list.add(0.0);
        list.add(saldo);

        dataModel.addRow(list.toArray());

        // Membersihkan input setelah berhasil dimasukkan ke database
        clear();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException | NumberFormatException e) {
    // Tangani exception dengan menampilkan pesan menggunakan JOptionPane
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cmb_jenkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jenkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jenkelActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();
int row = tbm.getSelectedRow();

try {
    koneksi(); // Membuat koneksi ke database

    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        throw new IllegalArgumentException("Pilih baris terlebih dahulu.");
    }

    // Mendapatkan data dari input pengguna
    String idUser = (String) dataModel.getValueAt(row, 0);

    // Hapus data dari database
    String deleteSql = "DELETE FROM Data_nasabah WHERE ID_User = ?";
    PreparedStatement deleteStatement = conn.prepareStatement(deleteSql);
    deleteStatement.setString(1, idUser);
    deleteStatement.executeUpdate();

    // Hapus data dari tabel
    dataModel.removeRow(row);

    clear();
    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
} catch (SQLException | NumberFormatException e) {
    // Tangani exception dengan menampilkan pesan menggunakan JOptionPane
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
        koneksi(); // Membuat koneksi ke database

        // Menyiapkan pernyataan SQL untuk pencarian berdasarkan ID_User, Nama, dan Alamat
        String searchSql = "SELECT * FROM Data_nasabah WHERE ID_User LIKE ? OR Nama LIKE ? OR Alamat LIKE ?";
        PreparedStatement searchStatement = conn.prepareStatement(searchSql);

        // Mengatur parameter untuk pencarian dengan menggunakan placeholder LIKE
        searchStatement.setString(1, "%" + txtSearch.getText() + "%"); // ID_User
        searchStatement.setString(2, "%" + txtSearch.getText() + "%"); // Nama
        searchStatement.setString(3, "%" + txtSearch.getText() + "%"); // Alamat

        // Jalankan kueri
        ResultSet resultSet = searchStatement.executeQuery();

        // Hapus tabel
        DefaultTableModel dataModel = (DefaultTableModel) tbm.getModel();
        dataModel.setRowCount(0);

        // Tampilkan hasil pencarian dalam tabel
        boolean found = false;
        while (resultSet.next()) {
            found = true;
            List<Object> list = new ArrayList<>();
            list.add(resultSet.getString("ID_User"));
            list.add(resultSet.getString("Nama"));
            list.add(resultSet.getString("Jenis_Kelamin"));
            list.add(resultSet.getString("Alamat"));
            list.add("Saldo Awal");
            list.add(resultSet.getDouble("Saldo"));
            list.add(0.0);
            list.add(resultSet.getDouble("Saldo"));

            dataModel.addRow(list.toArray());
        }

        // Tutup result set dan pernyataan
        resultSet.close();
        searchStatement.close();
        
         txtSearch.setText("");
        // Jika tidak ada data ditemukan, tampilkan JOptionPane
        if (!found) {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (SQLException e) {
        // Tangani pengecualian SQL
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Kelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambahsaldo;
    private javax.swing.JButton btn_tariksaldo;
    private javax.swing.JComboBox<String> cmb_jenkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tbm;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_saldoawal;
    private javax.swing.JTextField txt_tambahsaldo;
    private javax.swing.JTextField txt_tariksaldo;
    // End of variables declaration//GEN-END:variables
}
