/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB4;


/**
 *
 * @author Aharfi
 */
public class GUI_Kelola extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Kelola
     */
    public GUI_Kelola() {
        initComponents();
    }
    public void clear(){
        txt_id.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_saldoawal.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        cmb_jenkel = new javax.swing.JComboBox<>();
        txt_alamat = new javax.swing.JTextField();
        txt_saldoawal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        txt_tambahsaldo = new javax.swing.JTextField();
        txt_tariksaldo = new javax.swing.JTextField();
        btn_tambahsaldo = new javax.swing.JButton();
        btn_tariksaldo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        cmb_jenkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jenkelActionPerformed(evt);
            }
        });

        jLabel1.setText("ID                       :");

        jLabel2.setText("Nama                :");

        jLabel3.setText("Jenis Kelamin   :");

        jLabel4.setText("Alamat              :");

        jLabel5.setText("Saldo Awal       :");

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        txt_tambahsaldo.setText("0");

        txt_tariksaldo.setText("0");

        btn_tambahsaldo.setText("Tambah Saldo");
        btn_tambahsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahsaldoActionPerformed(evt);
            }
        });

        btn_tariksaldo.setText("Tarik Saldo");
        btn_tariksaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tariksaldoActionPerformed(evt);
            }
        });

        memo.setColumns(20);
        memo.setRows(5);
        jScrollPane1.setViewportView(memo);

        jLabel6.setText("Tambah Saldo :");

        jLabel7.setText("Tarik Saldo       :");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Pendataan Keuangan Pribadi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tariksaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_id)
                                .addComponent(txt_nama)
                                .addComponent(cmb_jenkel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_alamat)
                                .addComponent(txt_saldoawal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_tambahsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cetak)
                                .addGap(18, 18, 18)
                                .addComponent(btn_tambahsaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(btn_tariksaldo)
                                .addGap(18, 18, 18)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_jenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(txt_saldoawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tambahsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tariksaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cetak)
                            .addComponent(btn_tambahsaldo)
                            .addComponent(btn_tariksaldo)
                            .addComponent(btnClose))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahsaldoActionPerformed
        // TODO add your handling code here:
        memo.setText("");
        kelola_keuangan pribadi = new kelola_keuangan();
        pribadi.dataID(txt_id.getText());
        pribadi.dataNama(txt_nama.getText());
        //encapsulation
        pribadi.setAlamat(txt_alamat.getText());
        //done
        pribadi.dataSaldo(Double.parseDouble(txt_saldoawal.getText()));
        memo.append("========================================================================\n");
        memo.append(" \t\t  Kelola Keuangan Pribadi\n");
        memo.append("========================================================================\n");
        memo.append("ID User : " + pribadi.cetakID()+"\n");
        memo.append("Nama User : " + pribadi.cetakNama()+"\n");
        if(cmb_jenkel.getSelectedIndex()==0){
           memo.append("Jenis Kelamin : Laki - Laki\n");
        }else if(cmb_jenkel.getSelectedIndex()==1){
           memo.append("Jenis Kelamin : Perempuan\n");
        }
        //encapsulation
        memo.append("Alamat User : " + pribadi.getAlamat()+"\n");
        //done
        memo.append("Saldo Awal  : " + pribadi.cetakSaldo()+"\n");
        double tambah = Double.parseDouble(txt_tambahsaldo.getText());
        double hasiltambah = pribadi.cetakSaldo() + tambah;
        memo.append("Jumlah Penambahan : " +tambah+ "\n");
        memo.append("Saldo Akhir : " + hasiltambah + "\n");
        clear();
    }//GEN-LAST:event_btn_tambahsaldoActionPerformed

    private void btn_tariksaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tariksaldoActionPerformed
        // TODO add your handling code here:
        memo.setText("");
        kelola_keuangan pribadi = new kelola_keuangan();
        pribadi.dataID(txt_id.getText());
        pribadi.dataNama(txt_nama.getText());
        //encapsulation
        pribadi.setAlamat(txt_alamat.getText());
         //done
        pribadi.dataSaldo(Double.parseDouble(txt_saldoawal.getText()));
        memo.append("========================================================================\n");
        memo.append(" \t\t  Kelola Keuangan Pribadi\n");
        memo.append("========================================================================\n");
        memo.append("ID User : " + pribadi.cetakID()+"\n");
        memo.append("Nama User : " + pribadi.cetakNama()+"\n");
        if(cmb_jenkel.getSelectedIndex()==0){
           memo.append("Jenis Kelamin : Laki - Laki\n");
        }else if(cmb_jenkel.getSelectedIndex()==1){
           memo.append("Jenis Kelamin : Perempuan\n");
        }
        //encapsulation
        memo.append("Alamat User : " + pribadi.getAlamat()+"\n");
        //done
        memo.append("Saldo Awal  : " + pribadi.cetakSaldo()+"\n");
        double tambah = Double.parseDouble(txt_tambahsaldo.getText());
        double kurang = Double.parseDouble(txt_tariksaldo.getText());
        double hasiltambah = pribadi.cetakSaldo() + tambah;
        memo.append("Jumlah Penambahan : " +tambah+ "\n");
        memo.append("Saldo Sebelumnya : " + hasiltambah + "\n");
        memo.append("Jumlah Pengurangan : " +kurang+"\n");
        memo.append("Saldo Akhir : " + (hasiltambah - kurang) + "\n");
        clear();
    }//GEN-LAST:event_btn_tariksaldoActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        memo.setText("");
        kelola_keuangan pribadi = new kelola_keuangan();
        pribadi.dataID(txt_id.getText());
        pribadi.dataNama(txt_nama.getText());
        //encapsulation
        pribadi.setAlamat(txt_alamat.getText());
        //done
        pribadi.dataSaldo(Double.parseDouble(txt_saldoawal.getText()));
        memo.append("========================================================================\n");
        memo.append(" \t\t  Kelola Keuangan Pribadi\n");
        memo.append("========================================================================\n");
        memo.append("ID User : " + pribadi.cetakID()+"\n");
        memo.append("Nama User : " + pribadi.cetakNama()+"\n");
        if(cmb_jenkel.getSelectedIndex()==0){
           memo.append("Jenis Kelamin : Laki - Laki\n");
        }else if(cmb_jenkel.getSelectedIndex()==1){
           memo.append("Jenis Kelamin : Perempuan\n");
        }
        //encapsulation
        memo.append("Alamat User : " + pribadi.getAlamat()+"\n");
        //done
        memo.append("Saldo Awal  : " + pribadi.cetakSaldo()+"\n");
        clear();
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cmb_jenkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jenkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jenkelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Kelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_tambahsaldo;
    private javax.swing.JButton btn_tariksaldo;
    private javax.swing.JComboBox<String> cmb_jenkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea memo;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_saldoawal;
    private javax.swing.JTextField txt_tambahsaldo;
    private javax.swing.JTextField txt_tariksaldo;
    // End of variables declaration//GEN-END:variables
}
